game_name : "J League Winning Eleven 9"
gui:
  face_type: ["Build", "Original", "Preset"]
  skin_colour_max: 4
  face_id_max: 512
  hair_id_max: 2047
# You can get this offset with cheat engine if your values is in hex (base 16) please write it as it follows 
#ie if in cheat engine you have 20BC just put 0x before the value 0x20BC, if your value is decimal (base 10) just write the number

player_edit_mode : 0x20CC6B88
player:
  face_type:
    offset: 108
    shift: 2
    mask: 3
  skin_colour:
    offset: 91
    shift: 1
    mask: 3
  face_id:
    offset: 101
    shift: 3
    mask: 511
  hair_id:
    offset: 93
    shift: 0
    mask: 2047