game_name : "Pro Evolution Soccer 2008 SLES_549.13"
gui:
  face_type: ["Build", "DONT USE", "Preset"]
  skin_colour_max: 4
  face_id_max: 2048
  hair_id_max: 2047
# You can get this offset with cheat engine
player_edit_mode : 0x20CF64E4
player:
  face_type:
    offset: 103
    shift: 0
    mask: 3
  skin_colour:
    offset: 89
    shift: 6
    mask: 3
  face_id:
    offset: 101
    shift: 5
    mask: 2047
  hair_id:
    offset: 93
    shift: 0
    mask: 2047